### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by givemefivw** [Margular/frida-skeleton#57]
我使用Windows平台搭建adb及frida环境，而在Windows环境下运行主程序则会提示`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte`错误，我将项目文件夹lib.utils.shell.py中修改`err = p.stderr.read().decode(encoding="unicode_escape").strip()`后，报错消失，但是又出现新的问题`[ERROR] [WatchThread] error occurred when init frida thread: unknown arch:`
想求助下如何在Win环境下顺利对进程进行hook呢

**Comment by Margular** [comment]
Windows的确有时候会出现各种编码的问题，你可以试试将encoding改为其它的试试，例如encoding='utf-8'或者encoding='gbk'，如果都不行，那就试试改成如下：
`p.stderr.read().decode(encoding='utf-8', errors='backslashreplace').strip()`
期望得到反馈，看看如何完美修复这个问题，之前也有人反馈编码的问题，但是奇怪的是我从来没出现过编码的问题

**Comment by givemefivw** [comment]
感谢大大回复，不过试着修改编码之后还是这个错误，`[ERROR] [WatchThread] error occurred when init frida thread: unknown arch:`，我对代码不是很懂:(，大大方便留个邮箱吗，我将错误信息截图传给你

**Comment by Margular** [comment]
你可以将图片上传到图床，用Markdown填入外部链接

**Comment by givemefivw** [comment]
[![W3uaxH.png](https://z3.ax1x.com/2021/07/18/W3uaxH.png)
[![W3uURe.png](https://z3.ax1x.com/2021/07/18/W3uURe.png)
[![W3u0sA.png](https://z3.ax1x.com/2021/07/18/W3u0sA.png)
[![W3uwMd.png](https://z3.ax1x.com/2021/07/18/W3uwMd.png)

**Comment by givemefivw** [comment]
只有这个unkown arch这个错误。windows的编码我都试了一遍，仍然不行

**Comment by Margular** [comment]
手动执行`adb shell getprop ro.product.cpu.abi`看下输出结果是啥，看报错信息应该是检测不到架构，你可以在lib/core/frida_thread.py的第69行手动添加`self.arch = 架构名`，例如`self.arch = 'arm64'`

**Comment by Margular** [comment]
方便的话顺便提供下`adb shell getprop`的结果，我看看能否改下代码使其更通用，你这个是Mate 30吧？我这里也跑过Mate 30，没发现过这个问题

**Comment by givemefivw** [comment]
结果是x86
[![W3Urct.png](https://z3.ax1x.com/2021/07/18/W3Urct.png)
修改之后未有结果，尝试-l选项，发现不能列举设备，感觉是这里出了问题，我再排查下
[![W3UsjP.png](https://z3.ax1x.com/2021/07/18/W3UsjP.png)

**Comment by Margular** [comment]
看看是不是python里面调用adb有问题，你进python，然后用os.system执行adb试试

**Comment by givemefivw** [comment]
Windwos下的问题仍然未解决，不过我尝试使用虚拟机连接，夜神62001端口无法连接，雷电的5555可以正常连接，然后在ubuntu环境下使用脚本，可以正常运行并且也出现了Bypass SSL的字样

**Comment by FupengWang** [comment]
你配置好了adb环境变量吗? 我在没有配置好环境变量前遇到了和你一样的问题, 之后问题解决.

**Comment by givemefivw** [comment]
嗯嗯，我重新安装了adb，调整了一下环境变量，可以正常使用了，感谢
