### ISSUE TITLE
找不到文件没任何反应

### ISSUE THREAD

**Issue by keannen** [Margular/frida-skeleton#61]
![image](https://user-images.githubusercontent.com/57442557/134275527-55e30613-cd6c-40e2-864e-8e0f18027170.png)

**Comment by keannen** [comment]
python .\frida-skeleton.py -i -v

**Comment by Margular** [comment]
猜测是网络问题，你也可以选择手动下载对应版本的frida-server到手机的/data/local/tmp，这样就会跳过这个检测

**Comment by Margular** [comment]
是否解决了？

**Comment by keannen** [comment]
确实是网络问题，解决了，thx
