### ISSUE TITLE
触发Frida中的device.enumerate_processes方法后不稳定，经常重启

### ISSUE THREAD

**Issue by keannen** [Margular/frida-skeleton#62]
当前需求，清除手机中的frida进程。
有没有比较好的脚本或合适的adb命令？
谢谢老大解答

**Comment by keannen** [comment]
当手机重启后后续的程序貌似就断开了，一直在等待

**Comment by Margular** [comment]
我的工具在启动之前会自动杀掉之前的frida-server的，具体代码在：`https://github.com/Margular/frida-skeleton/blob/master/lib/core/frida_thread.py#L178`

**Comment by keannen** [comment]
是的，就是在这个文件里。不知道大家是否也会遇到这个重启的问题。
能否在不重启的情况下进行frida的启动与关闭操作

**Comment by Margular** [comment]
```bash
adb shell
ps -ef | grep frida-server
kill <frida server pid>
iptables -t nat -F # 清除iptables配置
```
